
// player menu y
#define ID_xe_playerMenu 2001
#define ID_xe_playerMenu_menuTitle -1
#define ID_xe_playerMenu_playersName 2009
#define ID_xe_playerMenu_buttonBackgroundClose -1
#define ID_xe_playerMenu_buttonClose 1002
#define ID_xe_playerMenu_moneyTitle -1
#define ID_xe_playerMenu_moneyBackground -1
#define ID_xe_playerMenu_moneyInfo 2015
#define ID_xe_playerMenu_moneyEdit 2018
#define ID_xe_playerMenu_moneyGive 2001
#define ID_xe_playerMenu_moneyNearPlayers 2022
#define ID_xe_playerMenu_inventoryTitle -1
#define ID_xe_playerMenu_inventoryBackground -1
#define ID_xe_playerMenu_inventoryList 2005
#define ID_xe_playerMenu_inventoryEdit 2010
#define ID_xe_playerMenu_inventoryNearPlayers 2023
#define ID_xe_playerMenu_inventoryUse 1014
#define ID_xe_playerMenu_inventoryGive 2002
#define ID_xe_playerMenu_inventoryRemove -1
#define ID_xe_playerMenu_buttonBackground01 2101
#define ID_xe_playerMenu_buttonBackground02 2102
#define ID_xe_playerMenu_buttonBackground03 2103
#define ID_xe_playerMenu_buttonBackground04 2104
#define ID_xe_playerMenu_buttonBackground05 2105
#define ID_xe_playerMenu_buttonBackground06 2106
#define ID_xe_playerMenu_buttonBackground07 2107
#define ID_xe_playerMenu_buttonBackground08 2108
#define ID_xe_playerMenu_buttonBackground09 2109
#define ID_xe_playerMenu_buttonBackground10 2110
#define ID_xe_playerMenu_buttonBackground11 2111
#define ID_xe_playerMenu_buttonBackground12 2112
#define ID_xe_playerMenu_buttonBackground13 2113
#define ID_xe_playerMenu_buttonBackground14 2114
#define ID_xe_playerMenu_buttonBackground15 2115
#define ID_xe_playerMenu_buttonLicenses -1
#define ID_xe_playerMenu_buttonKeys 2013
#define ID_xe_playerMenu_buttonGang 2011
#define ID_xe_playerMenu_buttonWantedList 2012
#define ID_xe_playerMenu_buttonPhone 2014
#define ID_xe_playerMenu_buttonSyncData -1
#define ID_xe_playerMenu_buttonSettings -1
#define ID_xe_playerMenu_buttonAdminMenu 2021

// licenses gui
#define ID_xe_licenseGui 8010
#define ID_xe_licenseGui_licenseBackground -1
#define ID_xe_licenseGui_licenseTitle -1
#define ID_xe_licenseGui_licenseBackgroundButtonClose -1
#define ID_xe_licenseGui_licenseButtonClose -1
#define ID_xe_licenseGui_licenseList -1
#define ID_xe_licenseGui_licenses 8011