
class xeCfg_backpacks {

    class Backpack_small { vInvSize = 26; };
    class Backpack_medium { vInvSize = 40; };
    class Backpack_big { vInvSize = 52; };

    class B_Parachute : Backpack_small {};

    class B_AssaultPack_blk : Backpack_small {};
    class B_AssaultPack_cbr : Backpack_small {};
    class B_AssaultPack_dgtl : Backpack_small {};
    class B_AssaultPack_eaf_F : Backpack_small {};
    class B_AssaultPack_khk : Backpack_small {};
    class B_AssaultPack_mcamo : Backpack_small {};
    class B_AssaultPack_ocamo : Backpack_small {};
    class B_AssaultPack_rgr : Backpack_small {};
    class B_AssaultPack_sgg : Backpack_small {};
    class B_AssaultPack_tna_F : Backpack_small {};
    class B_AssaultPack_wdl_F : Backpack_small {};
    class B_CivilianBackpack_01_Everyday_Astra_F : Backpack_small {};
    class B_CivilianBackpack_01_Everyday_Black_F : Backpack_small {};
    class B_CivilianBackpack_01_Everyday_IDAP_F : Backpack_small {};
    class B_CivilianBackpack_01_Everyday_Vrana_F : Backpack_small {};
    class B_CivilianBackpack_01_Sport_Blue_F : Backpack_small {};
    class B_CivilianBackpack_01_Sport_Green_F : Backpack_small {};
    class B_CivilianBackpack_01_Sport_Red_F : Backpack_small {};
    class B_FieldPack_blk : Backpack_small {};
    class B_FieldPack_cbr : Backpack_small {};
    class B_FieldPack_ghex_F : Backpack_small {};
    class B_FieldPack_green_F : Backpack_small {};
    class B_FieldPack_khk : Backpack_small {};
    class B_FieldPack_ocamo : Backpack_small {};
    class B_FieldPack_oli : Backpack_small {};
    class B_FieldPack_oucamo : Backpack_small {};
    class B_FieldPack_taiga_F : Backpack_small {};
    class B_Kitbag_cbr : Backpack_small {};
    class B_Kitbag_mcamo : Backpack_small {};
    class B_Kitbag_rgr : Backpack_small {};
    class B_Kitbag_sgg : Backpack_small {};
    class B_Kitbag_tan : Backpack_small {};
    class B_LegStrapBag_black_F : Backpack_small {};
    class B_LegStrapBag_coyote_F : Backpack_small {};
    class B_LegStrapBag_olive_F : Backpack_small {};
    class B_Messenger_Black_F : Backpack_small {};
    class B_Messenger_Coyote_F : Backpack_small {};
    class B_Messenger_Gray_F : Backpack_small {};
    class B_Messenger_IDAP_F : Backpack_small {};
    class B_Messenger_Olive_F : Backpack_small {};
    class B_TacticalPack_blk : Backpack_small {};
    class B_TacticalPack_mcamo : Backpack_small {};
    class B_TacticalPack_ocamo : Backpack_small {};
    class B_TacticalPack_oli : Backpack_small {};
    class B_TacticalPack_rgr : Backpack_small {};
    class B_ViperHarness_blk_F : Backpack_small {};
    class B_ViperHarness_ghex_F : Backpack_small {};
    class B_ViperHarness_hex_F : Backpack_small {};
    class B_ViperHarness_khk_F : Backpack_small {};
    class B_ViperHarness_oli_F : Backpack_small {};
    class B_ViperLightHarness_blk_F : Backpack_small {};
    class B_ViperLightHarness_ghex_F : Backpack_small {};
    class B_ViperLightHarness_hex_F : Backpack_small {};
    class B_ViperLightHarness_khk_F : Backpack_small {};
    class B_ViperLightHarness_oli_F : Backpack_small {};

    class B_Carryall_cbr : Backpack_medium {};
    class B_Carryall_eaf_F : Backpack_medium {};
    class B_Carryall_ghex_F : Backpack_medium {};
    class B_Carryall_green_F : Backpack_medium {};
    class B_Carryall_khk : Backpack_medium {};
    class B_Carryall_mcamo : Backpack_medium {};
    class B_Carryall_ocamo : Backpack_medium {};
    class B_Carryall_oli : Backpack_medium {};
    class B_Carryall_oucamo : Backpack_medium {};
    class B_Carryall_taiga_F : Backpack_medium {};
    class B_Carryall_wdl_F : Backpack_medium {};
    
    class B_Bergen_dgtl_F : Backpack_big {};
    class B_Bergen_hex_F : Backpack_big {};
    class B_Bergen_mcamo_F : Backpack_big {};
    class B_Bergen_tna_F : Backpack_big {};
};
